AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  clean-tablet games

Globals:
  Function:
    Timeout: 10

Resources:
  GamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri: handle/
      Handler: main
      Runtime: go1.x
      # Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      # Events:
      #   ApiEvent:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /{proxy+}
      #       Method: ANY
      # Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        # Variables:
        #   tableName: demo