package main

type desc struct {
	ZeroScores, OneScores, ThreeScores int
	Description                        string
}

var bunchOfTests = []struct {
	input       game
	expected    game
	description desc
}{
	{input: game{
		Players: livePlayerList{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    10,
				Answer:   "ans1",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    20,
				Answer:   "ans1",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "ans1",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "ans2",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    15,
				Answer:   "ans2",
			},
		},
		Answers:  map[string][]string{},
		Scores:   map[string]int{},
		HiScore:  0,
		GameTied: false,
	}, expected: game{
		Players: livePlayerList{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    21,
				Answer:   "",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    8,
				Answer:   "",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    14,
				Answer:   "",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    18,
				Answer:   "",
			},
		},
		Answers: map[string][]string{
			"ans1": {"p1", "p2", "p3"},
			"ans2": {"p4", "p5"},
		},
		Scores: map[string]int{
			"p1": 1,
			"p2": 1,
			"p3": 1,
			"p4": 3,
			"p5": 3,
		},
		HiScore:  21,
		GameTied: false,
	}, description: desc{
		ZeroScores:  0,
		OneScores:   3,
		ThreeScores: 2,
		Description: "no ties",
	}},
	{input: game{
		Players: livePlayerList{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    20,
				Answer:   "ans1",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    20,
				Answer:   "ans1",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "ans3",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "ans2",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    15,
				Answer:   "ans2",
			},
		},
		Answers:  map[string][]string{},
		Scores:   map[string]int{},
		HiScore:  0,
		GameTied: false,
	}, expected: game{
		Players: livePlayerList{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    23,
				Answer:   "",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    23,
				Answer:   "",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    14,
				Answer:   "",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    18,
				Answer:   "",
			},
		},
		Answers: map[string][]string{
			"ans1": {"p1", "p2"},
			"ans3": {"p3"},
			"ans2": {"p4", "p5"},
		},
		Scores: map[string]int{
			"p1": 3,
			"p2": 3,
			"p3": 0,
			"p4": 3,
			"p5": 3,
		},
		HiScore:  23,
		GameTied: true,
	}, description: desc{
		ZeroScores:  1,
		OneScores:   0,
		ThreeScores: 4,
		Description: "hiscore ties",
	}},
	{input: game{
		Players: livePlayerList{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    10,
				Answer:   "ans1",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    20,
				Answer:   "ans2",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "ans3",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "ans4",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    15,
				Answer:   "ans5",
			},
		},
		Answers:  map[string][]string{},
		Scores:   map[string]int{},
		HiScore:  0,
		GameTied: false,
	}, expected: game{
		Players: livePlayerList{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    10,
				Answer:   "",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    20,
				Answer:   "",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    15,
				Answer:   "",
			},
		},
		Answers: map[string][]string{
			"ans1": {"p1"},
			"ans2": {"p2"},
			"ans3": {"p3"},
			"ans4": {"p4"},
			"ans5": {"p5"},
		},
		Scores: map[string]int{
			"p1": 0,
			"p2": 0,
			"p3": 0,
			"p4": 0,
			"p5": 0,
		},
		HiScore:  20,
		GameTied: false,
	}, description: desc{
		ZeroScores:  5,
		OneScores:   0,
		ThreeScores: 0,
		Description: "nobody scores",
	}},
	{input: game{
		Players: livePlayerList{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    10,
				Answer:   "ans1",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    20,
				Answer:   "ans1",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "ans1",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "ans1",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    15,
				Answer:   "ans1",
			},
		},
		Answers:  map[string][]string{},
		Scores:   map[string]int{},
		HiScore:  0,
		GameTied: false,
	}, expected: game{
		Players: livePlayerList{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    21,
				Answer:   "",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    8,
				Answer:   "",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    12,
				Answer:   "",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    16,
				Answer:   "",
			},
		},
		Answers: map[string][]string{
			"ans1": {"p1", "p2", "p3", "p4", "p5"},
		},
		Scores: map[string]int{
			"p1": 1,
			"p2": 1,
			"p3": 1,
			"p4": 1,
			"p5": 1,
		},
		HiScore:  21,
		GameTied: false,
	}, description: desc{
		ZeroScores:  0,
		OneScores:   5,
		ThreeScores: 0,
		Description: "everybody scores 1",
	}},
}
