package main

var bunchOfTests = []struct {
	input       game
	expected    game
	description string
}{
	{input: game{
		Players: []livePlayer{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    10,
				Answer:   "ans1",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    20,
				Answer:   "ans1",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "ans1",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "ans2",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    15,
				Answer:   "ans2",
			},
		},
		Answers: map[string][]string{},
		Scores:  map[string]int{},
		Winner:  false,
	}, expected: game{
		Players: []livePlayer{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    21,
				Answer:   "",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    8,
				Answer:   "",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    14,
				Answer:   "",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    18,
				Answer:   "",
			},
		},
		Answers: map[string][]string{
			"ans1": {"p1", "p2", "p3"},
			"ans2": {"p4", "p5"},
		},
		Scores: map[string]int{
			"p1": 1,
			"p2": 1,
			"p3": 1,
			"p4": 3,
			"p5": 3,
		},
		Winner: false,
	}, description: "0:0, 1:3, 3:2, no winner",
	},
	{input: game{
		Players: []livePlayer{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    23,
				Answer:   "ans1",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    23,
				Answer:   "ans1",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "ans3",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "ans2",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    15,
				Answer:   "ans2",
			},
		},
		Answers: map[string][]string{},
		Scores:  map[string]int{},
		Winner:  false,
	}, expected: game{
		Players: []livePlayer{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    26,
				Answer:   "",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    26,
				Answer:   "",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    14,
				Answer:   "",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    18,
				Answer:   "",
			},
		},
		Answers: map[string][]string{
			"ans1": {"p1", "p2"},
			"ans3": {"p3"},
			"ans2": {"p4", "p5"},
		},
		Scores: map[string]int{
			"p1": 3,
			"p2": 3,
			"p3": 0,
			"p4": 3,
			"p5": 3,
		},
		Winner: false,
	}, description: "0:1, 1:0, 3:4, no winner - tied"},
	{input: game{
		Players: []livePlayer{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    10,
				Answer:   "ans1",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    20,
				Answer:   "ans2",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "ans3",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "ans4",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    15,
				Answer:   "ans5",
			},
		},
		Answers: map[string][]string{},
		Scores:  map[string]int{},
		Winner:  false,
	}, expected: game{
		Players: []livePlayer{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    10,
				Answer:   "",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    20,
				Answer:   "",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    15,
				Answer:   "",
			},
		},
		Answers: map[string][]string{
			"ans1": {"p1"},
			"ans2": {"p2"},
			"ans3": {"p3"},
			"ans4": {"p4"},
			"ans5": {"p5"},
		},
		Scores: map[string]int{
			"p1": 0,
			"p2": 0,
			"p3": 0,
			"p4": 0,
			"p5": 0,
		},
		Winner: false,
	}, description: "0:5, 1:0, 3:0, nobody scores, no winner",
	},
	{input: game{
		Players: []livePlayer{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    10,
				Answer:   "ans1",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    24,
				Answer:   "ans1",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "ans1",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "ans1",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    15,
				Answer:   "ans1",
			},
		},
		Answers: map[string][]string{},
		Scores:  map[string]int{},
		Winner:  false,
	}, expected: game{
		Players: []livePlayer{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    11,
				Answer:   "",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    25,
				Answer:   "",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    8,
				Answer:   "",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    12,
				Answer:   "",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    16,
				Answer:   "",
			},
		},
		Answers: map[string][]string{
			"ans1": {"p1", "p2", "p3", "p4", "p5"},
		},
		Scores: map[string]int{
			"p1": 1,
			"p2": 1,
			"p3": 1,
			"p4": 1,
			"p5": 1,
		},
		Winner: true,
	}, description: "0:0, 1:5, 3:0, everybody scores 1, winner",
	},
	{input: game{
		Players: []livePlayer{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    24,
				Answer:   "ans1",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    7,
				Answer:   "ans1",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    16,
				Answer:   "ans5",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    16,
				Answer:   "ans5",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    17,
				Answer:   "ans5",
			},
		},
		Answers: map[string][]string{},
		Scores:  map[string]int{},
		Winner:  false,
	}, expected: game{
		Players: []livePlayer{
			{
				PlayerID: "p1",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    27,
				Answer:   "",
			},
			{
				PlayerID: "p2",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    10,
				Answer:   "",
			},
			{
				PlayerID: "p3",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    17,
				Answer:   "",
			},
			{
				PlayerID: "p4",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    17,
				Answer:   "",
			},
			{
				PlayerID: "p5",
				Name:     "",
				ConnID:   "",
				Color:    "",
				Score:    18,
				Answer:   "",
			},
		},
		Answers: map[string][]string{
			"ans1": {"p1", "p2"},
			"ans5": {"p3", "p4", "p5"},
		},
		Scores: map[string]int{
			"p1": 3,
			"p2": 3,
			"p3": 1,
			"p4": 1,
			"p5": 1,
		},
		Winner: true,
	}, description: "0:0, 1:3, 3:2, winner",
	},
}
